# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-12 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('django_bouncy', '0006_auto_20181112_1119'), ('django_bouncy', '0007_auto_20181112_1219')]

    dependencies = [
        ('django_bouncy', '0005_auto_20181108_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounce',
            name='mail_messageid',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='mail_messageid',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='mail_messageid',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='bounce',
            name='json_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bounce',
            name='remote_mta_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='json_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='remote_mta_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='json_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='remote_mta_ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
